version: '3.1'

services:
  bocasujaapi:
   image: ghcr.io/programador-tv/bocasujaapi
   container_name: bocasujaapi
   restart: always
   ports:
    - 8001:80
   build: 
    context: ../../
    dockerfile: ./devops/docker/dockerfile.aspnet
    args:
      - PROJECT_NAME=Web.Api.BocaSuja
      - PROJECT_PATH=./Apps/Web.Api.BocaSuja
   env_file:
    - envs/aspnet.env
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    env_file:
      - envs/sqlserver.env
    ports:
    - 1433:1433
    volumes:
      - sql-storage:/var/opt/mssql
  
volumes:
  sql-storage:
