version: '3.1'

services:
  liveapi:
   image: ghcr.io/programador-tv/bocasujaapi
   container_name: bocasujaapi
   restart: always
   ports:
    - 8001:80
   build: 
    context: ../../
    dockerfile: ./devops/Docker/dockerfile.aspnet
    args:
      - PROJECT_NAME=Web.Api.BocaSuja
      - PROJECT_PATH=./Apps/Web.Api.BocaSuja
   env_file:
    - envs/aspnet.env
