version: '3.1'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: y
      SA_PASSWORD: FakeStrong@Passw0rd
      MSSQL_PID: Express
    ports: 
    - 1433:1433