apiVersion: v1
kind: Service
metadata:
  name: bocasujaapi
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: bocasujaapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80